Movie.create(title:"Pulp Fiction", release_year:1994, director:"Quentin Tarentino")
Movie.create(title:"Fight Club", release_year:1999, director:"David Fincher")
Movie.create(title:"Inception", release_year:2010, director:"Christopher Nolan")
Movie.create(title:"The Grand Budapest Hotel", release_year:2013, director:"Wes Anderson")
Movie.create(title:"La Haine", release_year:1995, director:"Mathieu Kassovitz")